version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.1.0

commands:
  terraform-install:
    parameters:
      version:
        default: 1.3.6
        type: string
    steps:
      - run:
          name: Install terraform
          command: |
            curl https://releases.hashicorp.com/terraform/<<parameters.version>>/terraform_<<parameters.version>>_linux_amd64.zip \
                --output terraform.zip --no-progress-meter
            ls -l
            unzip terraform.zip
            sudo mv terraform /usr/bin
  aws-web-auth:
    parameters:
      profile-name:
        default: aws-default
        type: string
    steps:
      - run:
          name: AWS Authentication
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile <<parameters.profile-name>>
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile <<parameters.profile-name>>
    
  create-service-roles:
    steps:    
      - run:
          name: Create service roles
          command: |
            python3 --version
            pip install -r utilities/requirements.txt
            chmod +x utilities/setDeploymentServiceAccessControl.py
            ls -l ~
            ls -l ~/.aws/credentials
            ls -l ~/.aws/config
            python3 utilities/setDeploymentServiceAccessControl.py
jobs:
  test:
    docker:
      - image: cimg/python:3.9.0
    steps:
      - checkout
      - terraform-install
      - aws-cli/install      
      - aws-web-auth:
          profile-name: cloud_user
      - create-service-roles
      
workflows:
  test:
    jobs:
      - test:
          context: [aws]

# VS Code Extension Version: 1.3.0